export const SELECT_CONTACT='SELECT_CONTACT';
export const CREATE_CONTACT='CREATE_CONTACT';
export const UPDATE_CONTACT='UPDATE_CONTACT';
export const DELETE_CONTACT='DELETE_CONTACT';
export const START_CONVERSATION='START_CONVERSATION';
export const END_CONVERSATION='END_CONVERSATION';
export const CREATE_CONVERSATION='CREATE_CONVERSATION';

